### ISSUE TITLE
Error in arguments of /bp start

### ISSUE THREAD

**Issue by Laauuu** [Leon167/BlockParty-2.0#4]
It seems that the plugin are looking for an argument in a wrong position.
/bp (0) start (1) arena (2)
The plugin search the "arena" argument in position 1.
![Captura de pantalla de 2020-02-18 09-22-26](https://user-images.githubusercontent.com/33169908/74735805-320f6900-5230-11ea-9461-1a70807ce673.png)

**Comment by Leon167** [comment]
Fixed in the next update (v2.0.3.5)!
