### ISSUE TITLE
Feature Request for Bungeecord - More setting options

### ISSUE THREAD

**Issue by Maximilian1021** [Leon167/BlockParty-2.0#48]
**Is your feature request related to a problem? Please describe.**
It refers to the bungee cord support. I would like to be able to set whether the server stays online and start a new round (current version) or whether the server restarts/stops after the round after a 30 sec. countdown (cloud systems), etc.

**Describe the solution you'd like**
Possibility to set whether a new round should start automatically or if the server should restart when a round is finished.

**Describe alternatives you've considered**
Currently I have no alternative solution for the problem

**Additional context**
I respond as soon as possible to your answers here in the issue

Written with much love and the thoughts of other users :)

**Comment by phm07** [comment]
Why would you want to stop the server everytime a game ends? This would waste resources since the plugin can start a new game after the old one ended. You can automatically kick all players after the game ended by setting `AutoKick` to `True` in your `Arenas/[Arena].yml`.

**Comment by Maximilian1021** [comment]
Thanks . i looking
