### ISSUE TITLE
You are not in arena

### ISSUE THREAD

**Issue by pixkk** [Leon167/BlockParty-2.0#57]
**Describe the bug**
When typing /reload, /stop commands, blockparty blocks them
![image](https://user-images.githubusercontent.com/30828435/202262610-0f6fe602-5801-4449-b501-35130bbeac6e.png)

**Environment):**
 - Server version: Spigot 1.16.5
 - BlockParty version [2.0.3.4]

**Comment by phm07** [comment]
Try /minecraft:stop

**Comment by pixkk** [comment]
> Try /minecraft:stop

Thx.
